### ISSUE TITLE
Update menu item titles and links

### ISSUE THREAD

**Issue by alfg** [alfg/somafm#5]
A few Menu items need to be updated.

Update title to SomaFM:
https://github.com/alfg/somafm/blob/master/app/menu.js#L50
https://github.com/alfg/somafm/blob/master/app/menu.js#L54

Replace the help menu titles and links:
https://github.com/alfg/somafm/blob/master/app/menu.js#L98
https://github.com/alfg/somafm/blob/master/app/menu.js#L161

Homepage - https://alfg.github.io/somafm
Github - https://github.com/alfg/somafm
Issues - https://github.com/alfg/somafm/issues
Releases - https://github.com/alfg/somafm/releases

Reference:
https://electron.atom.io/docs/api/menu/#examples

**Comment by Skowt** [comment]
Checking into this now 👀

**Comment by Skowt** [comment]
Should be done: https://github.com/alfg/somafm/pull/6
